create database QLKHDAM_PS38841;
use QLKHDAM_PS38841;
-- NHAN VIEN
CREATE TABLE NHANVIEN
(
MANV NVARCHAR(20) NOT NULL,
MATKHAU NVARCHAR(20) NOT NULL,
HOTEN NVARCHAR(50) NOT NULL,
VAITRO BIT NOT NULL,
PRIMARY KEY(MANV))
--CHUYEN DE
CREATE TABLE CHUYENDE
(
MACD NCHAR(5) NOT NULL,
TENCD NVARCHAR(50) NOT NULL,
HOCPHI FLOAT NOT NULL,
THOILUONG INT NOT NULL,
HINH NVARCHAR(255) NOT NULL,
MOTA NVARCHAR(255) NOT NULL,
PRIMARY KEY(MACD))
--NGUOI HOC
CREATE TABLE NGUOIHOC
(
MANH NVARCHAR(7) NOT NULL,
HOTEN NVARCHAR(50) NOT NULL,
GIOITINH BIT DEFAULT 1,
NGAYSINH DATE NOT NULL,
DIENTHOAI NVARCHAR(24) NOT NULL,
EMAIL NVARCHAR(255) not null,
GHICHU NVARCHAR(MAX) NULL,
MANV NVARCHAR(20) NOT NULL,
NGAYDK DATE DEFAULT GETDATE(),
constraint MANH primary key(MANH),
  Constraint fk_NH_NV foreign key(MANV) references NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE
)
--KHOA HOC
create table KHOAHOC
(
MaKH INT IDENTITY(1,1) NOT NULL,
MaCD NCHAR(5) NOT NULL,
HOCPHI FLOAT NOT NULL,
NGAYKG DATE NOT NULL,
GHICHU NVARCHAR(50) NULL,
MANV NVARCHAR(20) NOT NULL,
NGAYTAO DATE NOT NULL,
PRIMARY KEY(MAKH),
Constraint fk_KH_CD foreign key(MACD) references CHUYENDE(MACD) ON DELETE NO ACTION ON UPDATE CASCADE,
Constraint fk_KH_NV foreign key(MANV) references NHANVIEN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE)
--HOC VIEN
CREATE TABLE HOCVIEN
(
MAHV INT IDENTITY(1,1) NOT NULL,
MAKH INT NOT NULL,
MANH NVARCHAR(7) NOT NULL,
DIEM FLOAT DEFAULT -1,
PRIMARY KEY(MAHV),
Constraint fk_HV_KH foreign key(MAKH) references KHOAHOC(MAKH),
Constraint fk_HV_NH foreign key(MANH) references NGUOIHOC(MANH))
--PROC 
GO
--BANG DIEM
CREATE PROC SP_BANGDIEM(@MAKH INT)
AS BEGIN
SELECT 
	NH.MANH,NH.HOTEN,HV.DIEM
FROM HOCVIEN HV
	JOIN NGUOIHOC NH ON NH.MANH=HV.MAHV
WHERE HV.MAKH=@MAKH
ORDER BY HV.DIEM DESC
END
GO
--THONG KE DIEM
CREATE PROC SP_THONGKEDIEM
AS BEGIN
SELECT 
	TENCD CHUYENDE,
	COUNT(MAHV) SOHV,
	MIN(DIEM) THAPNHAT,
	MAX(DIEM) CAONHAT,
	AVG(DIEM) TRUNGBINH
FROM KHOAHOC KH 
	JOIN HOCVIEN HV ON KH.MAKH=HV.MAKH
	JOIN CHUYENDE CD ON CD.MACD=KH.MaCD
	GROUP BY TENCD
END
GO
--DOANH THU
CREATE PROC SP_THONGKEDOANHTHU(@YEAR INT)
AS BEGIN
SELECT 
	TENCD CHUYENDE,
	COUNT(DISTINCT KH.MAKH) SOKH,
	COUNT(HV.MAHV) SOHV,
	SUM(KH.HOCPHI) DOANHTHU,
	MIN(KH.HOCPHI) THAPNHAT,
	MAX(KH.HOCPHI) CAONHAT,
	AVG(KH.HOCPHI) TRUNGBINH
FROM KHOAHOC KH
	JOIN HOCVIEN HV ON KH.MAKH=HV.MAKH
	JOIN CHUYENDE CD ON CD.MACD=KH.MaCD
WHERE YEAR(NGAYKG)=@YEAR
GROUP BY  TENCD
END
GO
--THONG KE NGUOI HOC
CREATE PROC SP_THONGKENGUOIHOC
AS BEGIN
SELECT 
	YEAR(NGAYDK) NAM,
	COUNT(*) SOLUONG,
	MIN(NGAYDK) DAUTIEN,
	MAX(NGAYDK) CUOICUNG
FROM NGUOIHOC
GROUP BY YEAR(NGAYDK)
END
GO