/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package giaodien;

import com.edusys.utlis.Auth;
import com.edusys.utlis.TBBOX;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Nam
 */
public class EDUSYSJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EDUSYSJFrame
     */
    void xetuser(){
        if(Auth.isLogin()==false){
            TBBOX.alert(this, "BẠN CHƯA ĐĂNG NHẬP");
            System.exit(0);
        }
        xetvaitro();
        
    }
    void xetvaitro(){
        if(Auth.isManager()){
            trangthai.setText("Trưởng Phòng");
        }
        else{
            trangthai.setText("Nhân Viên");
            btnDTHU.setEnabled(false);
            
        }
    }
    public EDUSYSJFrame() {
        initComponents();
         this.setLocationRelativeTo(null);
          Image icon = new ImageIcon(this.getClass().getResource("/com/edusys/Icon Application/fpt.png")).getImage();
        this.setIconImage(icon);
        new ChaoJDialog(this, true).setVisible(true);
        new DangnhapJDialog(this, true).setVisible(true);
        init();
        xetuser();
        xetvaitro();
    }
//    void openDoiMatKhau(){
//        if (auth.islogin)
//        new DoimatkhauJDialog(this, true).setVisible(true);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        btnkt = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        butNH = new javax.swing.JButton();
        btnKH = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        butHV = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        trangthai = new javax.swing.JLabel();
        lbtimer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btndmk = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btncd = new javax.swing.JMenuItem();
        btnkh = new javax.swing.JMenuItem();
        btnNH = new javax.swing.JMenuItem();
        btnHV = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnNV = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnBD = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        btnLNH = new javax.swing.JMenuItem();
        btnDCD = new javax.swing.JMenuItem();
        btnDTHU = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnhdsd = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btnGTSP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lập Trình City-Education Management System");

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Log out.png"))); // NOI18N
        jButton1.setText("Đăng xuất");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        btnkt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Delete.png"))); // NOI18N
        btnkt.setText("Kết thúc");
        btnkt.setFocusable(false);
        btnkt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnkt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnktActionPerformed(evt);
            }
        });
        jToolBar1.add(btnkt);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Address book.png"))); // NOI18N
        jButton4.setText("Chuyên đề");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        butNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/User.png"))); // NOI18N
        butNH.setText("Người học");
        butNH.setFocusable(false);
        butNH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butNH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNHActionPerformed(evt);
            }
        });
        jToolBar1.add(butNH);

        btnKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Task list.png"))); // NOI18N
        btnKH.setText("Khóa học");
        btnKH.setFocusable(false);
        btnKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKH);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Address book.png"))); // NOI18N
        jButton8.setText("Hướng dẫn");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        butHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Users.png"))); // NOI18N
        butHV.setText("Học viên");
        butHV.setFocusable(false);
        butHV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butHV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHVActionPerformed(evt);
            }
        });
        jToolBar1.add(butHV);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        trangthai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Refresh.png"))); // NOI18N
        trangthai.setText("Thông tin trạng thái");

        lbtimer.setText("timer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(trangthai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbtimer)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trangthai)
                    .addComponent(lbtimer)))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/trumpbee.png"))); // NOI18N

        jMenu1.setText("Hệ Thống");

        btndmk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Refresh.png"))); // NOI18N
        btndmk.setText("Đổi mật khẩu");
        btndmk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndmkActionPerformed(evt);
            }
        });
        jMenu1.add(btndmk);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Exit.png"))); // NOI18N
        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Delete.png"))); // NOI18N
        jMenuItem3.setText("Kết thúc");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        btncd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btncd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Task list.png"))); // NOI18N
        btncd.setText("Chuyên đề");
        btncd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncdActionPerformed(evt);
            }
        });
        jMenu2.add(btncd);

        btnkh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnkh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Numbered list.png"))); // NOI18N
        btnkh.setText("Khóa học");
        btnkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkhActionPerformed(evt);
            }
        });
        jMenu2.add(btnkh);

        btnNH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Unknown person.png"))); // NOI18N
        btnNH.setText("Người học");
        btnNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNHActionPerformed(evt);
            }
        });
        jMenu2.add(btnNH);

        btnHV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/User.png"))); // NOI18N
        btnHV.setText("Học Viên");
        btnHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHVActionPerformed(evt);
            }
        });
        jMenu2.add(btnHV);
        jMenu2.add(jSeparator1);

        btnNV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Users.png"))); // NOI18N
        btnNV.setText("Nhân viên");
        btnNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVActionPerformed(evt);
            }
        });
        jMenu2.add(btnNV);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        btnBD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        btnBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Task list.png"))); // NOI18N
        btnBD.setText("Bảng điểm");
        btnBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBDActionPerformed(evt);
            }
        });
        jMenu3.add(btnBD);
        jMenu3.add(jSeparator2);

        btnLNH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        btnLNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/List.png"))); // NOI18N
        btnLNH.setText("Lượng người học");
        btnLNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLNHActionPerformed(evt);
            }
        });
        jMenu3.add(btnLNH);

        btnDCD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        btnDCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Bar chart.png"))); // NOI18N
        btnDCD.setText("Điểm chuyên đề");
        btnDCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDCDActionPerformed(evt);
            }
        });
        jMenu3.add(btnDCD);

        btnDTHU.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        btnDTHU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Statistics.png"))); // NOI18N
        btnDTHU.setText("Doanh thu");
        btnDTHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDTHUActionPerformed(evt);
            }
        });
        jMenu3.add(btnDTHU);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        btnhdsd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        btnhdsd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Refresh.png"))); // NOI18N
        btnhdsd.setText("Hướng dẫn sử dụng");
        jMenu4.add(btnhdsd);
        jMenu4.add(jSeparator3);

        btnGTSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/Icon Application/Home.png"))); // NOI18N
        btnGTSP.setText("Giới thiệu sản phẩm");
        btnGTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGTSPActionPerformed(evt);
            }
        });
        jMenu4.add(btnGTSP);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btncdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncdActionPerformed
       this.openQuanlyCD();
    }//GEN-LAST:event_btncdActionPerformed

    private void btnktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnktActionPerformed
    System.exit(WIDTH);
    }//GEN-LAST:event_btnktActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       System.exit(WIDTH);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btndmkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndmkActionPerformed
      this.opendoimk();
    }//GEN-LAST:event_btndmkActionPerformed

    private void btnkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkhActionPerformed
      this.openQuanlyKH();
    }//GEN-LAST:event_btnkhActionPerformed

    private void btnNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNHActionPerformed
       this.openQuanlyNH();
    }//GEN-LAST:event_btnNHActionPerformed

    private void btnHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHVActionPerformed
      this.openQuanlyHV();
    }//GEN-LAST:event_btnHVActionPerformed

    private void btnNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNVActionPerformed
        this.QuanlyNV();
    }//GEN-LAST:event_btnNVActionPerformed

    private void btnBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBDActionPerformed
       this.openThongKeBD();
    }//GEN-LAST:event_btnBDActionPerformed

    private void btnLNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLNHActionPerformed
       this.openThongKeBD();
    }//GEN-LAST:event_btnLNHActionPerformed

    private void btnDCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDCDActionPerformed
     this.openThongKeBD();
    }//GEN-LAST:event_btnDCDActionPerformed

    private void btnDTHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDTHUActionPerformed
         this.openThongKeBD();
    }//GEN-LAST:event_btnDTHUActionPerformed

    private void btnGTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGTSPActionPerformed
        this.openGTSP();
    }//GEN-LAST:event_btnGTSPActionPerformed

    private void butHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHVActionPerformed
       this.openQuanlyHV();
    }//GEN-LAST:event_butHVActionPerformed

    private void btnKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKHActionPerformed
       this.openQuanlyKH();
    }//GEN-LAST:event_btnKHActionPerformed

    private void butNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNHActionPerformed
        this.openQuanlyNH();
    }//GEN-LAST:event_butNHActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      this.openQuanlyCD();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(TBBOX.confirm(this,"Đăng Xuất")){
            Auth.clear();
        if(Auth.isLogin()==false){
            TBBOX.alert(this, "BẠN Đã Đăng Xuất");
            if(TBBOX.confirm(this,"Bạn có muốn đăng nhập")){
                this.opendn();
                xetuser();
            }
            else{
                System.exit(0);
            }
        } 
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(TBBOX.confirm(this,"Đăng Xuất")){
            Auth.clear();
        if(Auth.isLogin()==false){
            TBBOX.alert(this, "BẠN Đã Đăng Xuất");
            if(TBBOX.confirm(this,"Bạn có muốn đăng nhập")){
                this.opendn();
                xetuser();
            }
            else{
                System.exit(0);
            }
        } 
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDUSYSJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDUSYSJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDUSYSJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDUSYSJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDUSYSJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnBD;
    private javax.swing.JMenuItem btnDCD;
    private javax.swing.JMenuItem btnDTHU;
    private javax.swing.JMenuItem btnGTSP;
    private javax.swing.JMenuItem btnHV;
    private javax.swing.JButton btnKH;
    private javax.swing.JMenuItem btnLNH;
    private javax.swing.JMenuItem btnNH;
    private javax.swing.JMenuItem btnNV;
    private javax.swing.JMenuItem btncd;
    private javax.swing.JMenuItem btndmk;
    private javax.swing.JMenuItem btnhdsd;
    private javax.swing.JMenuItem btnkh;
    private javax.swing.JButton btnkt;
    private javax.swing.JButton butHV;
    private javax.swing.JButton butNH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbtimer;
    private javax.swing.JLabel trangthai;
    // End of variables declaration//GEN-END:variables

    private void init() {
 new Timer(1000,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              Date now= new Date();
                SimpleDateFormat formater=new SimpleDateFormat("hh:mm:ss a");
                lbtimer.setText(formater.format(now));
            }
        }).start();
    }

    private void openQuanly() {
      new QuanlyNHJDialog(this, true).setVisible(true);
    }
    private void opendn() {
      new DangnhapJDialog(this, true).setVisible(true);
    }

    private void opendoimk() {
        new DoimatkhauJDialog(this, true).setVisible(true);
    }

    private void openQuanlyCD() {
       new QuanlyCDJDialog(this,true).setVisible(true);
    }

    private void openQuanlyKH() {
       new QuanlyKHJDialog(this,true).setVisible(true);
    }
//nguoi hoc
    private void openQuanlyNH() {
       new QuanlyNHJDialog(this,true).setVisible(true);
    }

    private void openQuanlyHV() {
        new QuanlyHVJDialog(this, true).setVisible(true);
    }

    private void QuanlyNV() {
       new QuanlyNVJDialog(this, true).setVisible(true);
    }

    private void openThongKeBD() {
       new ThongKeJDialog(this, true).setVisible(true);
    }

    private void openGTSP() {
       new GioiThieuJDialog(this, true).setVisible(true);
    }

   
}
